backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{

    /**
     * Lists all Inventory.
     * @return mixed
     */
    public function actionInventory()
    {
        return $this->render('inventory');
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'index','inventory'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'error', 'index','inventory'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'ROBOTS Corporation Inventory';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>ROBOTS Corporation Inventory</h1>

        <p class="lead">Operator menu</p>
        <p><a class="btn btn-default" href="<?= Url::to(['site/inventory']); ?>">Просмотр Инвенторя</a></p>

    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-2">
                <h2>Person</h2>
                <p>Люди используют Сервисы с помощью Аккаунтов.</p>
                <p><a class="btn btn-default" href="<?= Url::to(['person/index']); ?>">Работать с Людьми</a></p>
            </div>
            <div class="col-lg-2">
                <h2>Сервисы</h2>
                <p>Сервисы которыми могут воспользоваться Люди.</p>
                <p><a class="btn btn-default" href="<?= Url::to(['service/index']); ?>">Работать с Сервисами</a></p>
            </div>
            <div class="col-lg-3">
                <h2>Аккаунты</h2>
                <p>Аккаунты зареганные на Сервисах.</p>
                <p><a class="btn btn-default" href="<?= Url::to(['account/index']); ?>">Работать с Аккаунтами</a></p>
            </div>
            <div class="col-lg-3">
                <h2>Заметки</h2>
                <p>Заметки для размещения на сервисах.</p>
                <p><a class="btn btn-default" href="<?= Url::to(['post/index']); ?>">Работать с Заметками</a></p>
            </div>
            <div class="col-lg-2">
                <h2>Tag</h2>
                <p>Тэги - ярлычки которые при необходимости можно прикрепить к Персоне, Сервису, Аккаунту или Посту.</p>
            </div>
        </div>

    </div>
</div>

backend/views/site/inventory.php
<?php

/* @var $this yii\web\View */

use backend\models\Person;

$this->title = 'Persons and them accounts';

$sql = "
SELECT 
  (
  SELECT 
  a.login 
  FROM person ps 
  JOIN person_account pa
  ON ps.id = pa.person_id
  JOIN account a 
  ON pa.account_id = a.id
  JOIN service s ON 
  a.service_id = s.id
  WHERE
   ps.id = p.id
   AND s.code = 'MAIL_RU'
  ) AS login_mail_ru, 
  (
  SELECT 
  a.password 
  FROM person ps 
  JOIN person_account pa
  ON ps.id = pa.person_id
  JOIN account a 
  ON pa.account_id = a.id
  JOIN service s ON 
  a.service_id = s.id
  WHERE
   ps.id = p.id
   AND s.code = 'MAIL_RU'
  ) AS password_mail_ru,
  (
  SELECT 
  a.login 
  FROM person ps 
  JOIN person_account pa
  ON ps.id = pa.person_id
  JOIN account a 
  ON pa.account_id = a.id
  JOIN service s ON 
  a.service_id = s.id
  WHERE
   ps.id = p.id
   AND s.code = 'PIKABU_RU'
  ) AS login_pikabu_ru, 
  (
  SELECT 
  a.password 
  FROM person ps 
  JOIN person_account pa
  ON ps.id = pa.person_id
  JOIN account a 
  ON pa.account_id = a.id
  JOIN service s ON 
  a.service_id = s.id
  WHERE
   ps.id = p.id
   AND s.code = 'PIKABU_RU'
  ) AS password_pikabu_ru,
  (
  SELECT 
  a.login 
  FROM person ps 
  JOIN person_account pa
  ON ps.id = pa.person_id
  JOIN account a 
  ON pa.account_id = a.id
  JOIN service s ON 
  a.service_id = s.id
  JOIN tag_service ts 
  ON s.id = ts.service_id
  JOIN tag t 
  ON ts.tag_id = t.id
  WHERE
   ps.id = p.id
   AND t.code = 'PROXY'
  ) AS login_proxy, 
  (
  SELECT 
  a.password 
  FROM person ps 
  JOIN person_account pa
  ON ps.id = pa.person_id
  JOIN account a 
  ON pa.account_id = a.id
  JOIN service s ON 
  a.service_id = s.id
  JOIN tag_service ts 
  ON s.id = ts.service_id
  JOIN tag t 
  ON ts.tag_id = t.id
  WHERE
   ps.id = p.id
   AND t.code = 'PROXY'
  ) AS password_proxy, 
  (
  SELECT 
  s.code 
  FROM person ps 
  JOIN person_account pa
  ON ps.id = pa.person_id
  JOIN account a 
  ON pa.account_id = a.id
  JOIN service s ON 
  a.service_id = s.id
  JOIN tag_service ts 
  ON s.id = ts.service_id
  JOIN tag t 
  ON ts.tag_id = t.id
  WHERE
   ps.id = p.id
   AND t.code = 'PROXY'
  ) AS address_proxy, 
  (
  SELECT 
  t.code 
  FROM person ps 
  JOIN person_account pa
  ON ps.id = pa.person_id
  JOIN account a 
  ON pa.account_id = a.id
  JOIN service s ON 
  a.service_id = s.id
  JOIN tag_account ts 
  ON a.id = ts.account_id
  JOIN tag t 
  ON ts.tag_id = t.id
  WHERE
   ps.id = p.id
   AND s.code = 'PIKABU_RU'
   LIMIT 1
  ) AS pikabu_tag
  
FROM 
  person p
  ORDER BY p.id
;
";

$query = Person::getDb()->createCommand($sql)->query();
$data = $query->readAll();

$dataCount = count($data);
$isExists = $dataCount > 0;

if($isExists):
    ?>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                proxy login
            </th>
            <th>
                proxy password
            </th>
            <th>
                proxy
            </th>
            <th>
                pikabu login
            </th>
            <th>
                pikabu password
            </th>
            <th>
                mail login
            </th>
            <th>
                mail password
            </th>
            <th>
                pikabu tag
            </th>
        </tr>
        </thead>
        <tfoot>

        </tfoot>

        <?php foreach ( $data as $index => $row ):
            ?>
            <tr>
                <td>
                    <?= $index ?>
                </td>
                <td>
                    <?= $row['login_proxy'] ?>
                </td>
                <td>
                    <?= $row['password_proxy'] ?>
                </td>
                <td>
                    <?= $row['address_proxy'] ?>
                </td>
                <td>
                    <?= $row['login_pikabu_ru'] ?>
                </td>
                <td>
                    <?= $row['password_pikabu_ru'] ?>
                </td>
                <td>
                    <?= $row['login_mail_ru'] ?>
                </td>
                <td>
                    <?= $row['password_mail_ru'] ?>
                </td>
                <td>
                    <?= $row['pikabu_tag'] ?>
                </td>
            </tr>
        <?php endforeach; ?>

    </table>

<?php endif; ?>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>